layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 13
  exclude:
    archived: false
    forks: true
    #projects:
    #- 

  social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  #linkedin: linkedin.com/in/aashiq-ramachandran
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Cyber Security
    web_url: https://github.com/topics/cyber-security
    image_url:
    
  - name: Cyber Research
    web_url: https://github.com/topics/cyber-research
    image_url:

  - name: Security Operations
    web_url: https://github.com/topics/siem
    
  - name: Penetration Testing
    web_url: https://github.com/topics/penetration-testing
    
  - name: DevSecOps
    web_url: https://github.com/topics/devsecops
    
  - name: Cyber Forensics
    web_url: https://github.com/topics/digital-forensics
    
  - name: Social Engineering
    web_url: https://github.com/topics/social-engineering
    
  - name: Psychology
    web_url: https://github.com/topics/psychology

